if (!nexacro.translation) {
    nexacro.translation = {};
}
nexacro.translation["ja"] = {
    "인사": "こんにちは {{name}}",
    "error": {
        "invalid": "無効な値"
    },
	"warn":{
		"quit":"本当にやめたいの？",
		"menulimit": "メニューを10つ以上オープンできません。",
		"menuidnotexist":"メニューIDが存在しません。"
	},	
    "Animation":"アニメーション",
    "Application sample":"アプリケーションサンプル",
    "Average":"平均値",
    "Bidirectional data binding":"双方向データバインディング",
    "Capacity Usage":"容量の使用状況",
    "Category grid":"カテゴリグリッド",
    "Chart":"チャート",
    "Close all":"すべて閉じる",
    "Component":"コンポーネント",
    "Component dynamic creation":"コンポーネントの動的作成",
    "Components":"コンポーネント",
    "Content":"コンテンツ",
    "Convenient component placement":"コンポーネントの配置が簡単",
    "Convenient responsive web development":"便利で応答性の高いWeb開発",
    "Daily":"デイリー",
    "Dataset":"データセット",
    "Dynamic grid":"動的グリッド",
    "Dynamic tree grid":"動的ツリーグリッド",
    "Easy data visualization component":"簡単なデータ可視化コンポーネント",
    "Effectively Driven data on":"効果的に推進されるデータ",
    "Excel\r\r\nImport/Export":"Excel\nインポートエクスポート",
    "Excel Formula Import / Export":"Excel数式のインポートエクスポート",
    "Experience it on mobile!":"モバイルで体験してみてください!",
    "Extension component":"拡張コンポーネント",
    "File upload / download":"ファイルのアップロードダウンロード",
    "Fit To Contents":"コンテンツへの適合",
    "Google Map":"Googleマップ",
    "Grid":"グリッド",
    "Grid Component":"グリッドコンポーネント",
    "Grid cursor movement":"グリッドカーソル移動",
    "Guide":"ガイド",
    "Large data inquiry":"大規模なデータ照会",
    "List view":"リストビュー",
    "Log":"ログ",
    "MENU":"メニュー",
    "Nexacro Chart":"ネクサクロチャート",
    "Open all":"すべてを開く",
    "Personalization settings":"パーソナライゼーション設定",
    "Portlet screen":"ポートレット画面",
    "Quick Menu":"クイックメニュー",
    "Recently accessed menu":"最近アクセスしたメニュー",
    "Sample":"サンプル",
    "Screen personalization":"画面のパーソナライズ",
    "Send Message":"メッセージの送信",
    "Send post data to Server":"投稿データをサーバに送信する",
    "Static, Edit, MaskEdit, TextArea":"[Static]、[Edit]、[MaskEdit]、[TextArea]",
    "Support\r\nMultilingual":"多言語対応",
    "Tab, GroupBox, ProgressBar":"タブ、グループボックス、経過表示バー",
    "To Users":"ユーザへ",
    "Total Views":"総ビュー数",
    "Tree grid":"ツリーグリッド",
    "TreeGrid/\r\nGrouping":"ツリーグリッド\nグループ化",
    "Use external modules":"外部モジュールの使用",
    "Various components":"各種コンポーネント",
    "Various grid expressions":"さまざまなグリッド式",
    "Various grid functions":"さまざまなグリッド関数",
    "Various menu expressions":"各種メニュー表現",
    "WeChat":"ウィチャット",
    "Weekly":"週刊誌",
    "Weekly Report":"週報",
    "nexacro Chart":"Nexacroチャート",
    "nexacro platform demo":"Nexacroデモ",
    "pivot":"枢軸",
	"companyContact": "〒101-0021 東京都千代田区外神田5-3-1 秋葉原OSビル10F 電話番号：03-5812-6358（代表）\nCOPYRIGHT(C) BY 2020 Nexaweb Japan,Inc. ALL RIGHTS RESERVED",	
	"wechatsample": {
		"alert": {
			"touser":"「ユーザへ」フィールドに入力してください。",
			"content":"「コンテンツ」欄にご記入ください。"
		},	
		"explain": "データオブジェクトは、データを呼び出したり、管理したりするオブジェクトです。\r\n\r\nRESTAPI呼び出し関数とデータセットオブジェクトとの一方向バインディングをサポートします。\r\n\r\nデータオブジェクトの要求方式を使用してサーバと通信できます。\r\nこの場合、XMLHttpRequestオブジェクトは内部的に使用されます。",
	},
	"download": {
		"download":"ダウンロード",
		"ios": "iOS用ダウンロード",
		"macos": "macOS用ダウンロード",
		"android": "Android用ダウンロード",
		"windows64": "Windows64ビット用ダウンロード",
		"windows32": "Windows32ビット用ダウンロード"
	}
}