if (!nexacro.translation) {
    nexacro.translation = {};
}
nexacro.translation["ko"] = {
    "인사": "안녕하세요 {{name}}",
    "error": {
        "invalid": "잘못 된 값"
    },
	"warn":{
		"quit":"정말 종료 하시겠습니까?",
		"menulimit": "메뉴를 10개이상 오픈할 수 없습니다.",
		"menuidnotexist":"메뉴 ID가 존재하지 않습니다."
	},	
    "Animation":"애니메이션",
    "Application sample":"응용 샘플",
    "Average":"평균",
    "Bidirectional data binding":"양방향 데이터 바인딩",
    "Capacity Usage":"사용량",
    "Category grid":"카테고리 그리드",
    "Chart":"차트",
    "Close all":"모두 닫기",
    "Component":"컴포넌트",
    "Component dynamic creation":"컴포넌트 동적 생성",
    "Components":"컴포넌트",
    "Content":"내용",
    "Convenient component placement":"편리한 컴포넌트 배치",
    "Convenient responsive web development":"편리한 대응형 웹 개발",
    "Daily":"매일",
    "Dataset":"Dataset",
    "Dynamic grid":"동적 그리드",
    "Dynamic tree grid":"동적 트리 그리드",
    "Easy data visualization component":"간편한 데이터 시각화 구성 요소",
    "Effectively Driven data on":"효율적인 데이터 활용",
    "Excel\r\r\nImport/Export":"Excel\n가져오기/내보내기",
    "Excel Formula Import / Export":"Excel Formula 가져오기",
    "Experience it on mobile!":"모바일에서 직접 경험해 보세요!",
    "Extension component":"확장 컴포넌트",
    "File upload / download":"파일 업로드/다운로드",
    "Fit To Contents":"내용 자동 맞춤",
    "Google Map":"구글맵",
    "Grid":"Grid",
    "Grid Component":"그리드 컴포넌트",
    "Grid cursor movement":"그리드 커서 이동",
    "Guide":"가이드",
    "Large data inquiry":"대용량 자료 조회",
    "List view":"리스트뷰",
    "Log":"로그",
    "MENU":"메뉴",
    "Nexacro Chart":"넥사크로 차트",
    "Open all":"모두 열기",
    "Personalization settings":"개인화 설정",
    "Portlet screen":"포틀렛 화면",
    "Quick Menu":"퀵 메뉴",
    "Recently accessed menu":"최근 접속한 메뉴",
    "Sample":"샘플",
    "Screen personalization":"화면 개인화",
    "Send Message":"메시지 보내기",
    "Send post data to Server":"서버로 POST 데이터 전송",
    "Static, Edit, MaskEdit, TextArea":"Static, Edit, MaskEdit, TextArea",
    "Support\r\nMultilingual":"지원\n다국어",
    "Tab, GroupBox, ProgressBar":"Tab, GroupBox, ProgressBar",
    "To Users":"사용자",
    "Total Views":"전체 Views",
    "Tree grid":"트리 그리드",
    "TreeGrid/\r\nGrouping":"트리그리드/\n그룹화",
    "Use external modules":"외부 모듈 사용",
    "Various components":"다양한 컴포넌트",
    "Various grid expressions":"다양한 그리드 표현",
    "Various grid functions":"다양한 그리드 기능",
    "Various menu expressions":"다양한 메뉴 표현",
    "WeChat":"위챗",
    "Weekly":"주간",
    "Weekly Report":"주간 보고서",
    "nexacro Chart":"넥사크로 차트",
    "nexacro platform demo":"넥사크로 데모",
    "pivot":"피벗",
	"companyContact": "서울시 강남구 봉은사로 617 | 대표번호 : 02-2140-7700\nCOPYRIGHT(C) BY 2020 TOBESOFT.CO.LTD. ALL RIGHTS RESERVED",	
	"wechatsample": {
		"alert": {
			"touser":"사용자 정보를 입력하세요.",
			"content":"내용을 입력하세요."
		},	
		"explain": "Dataobject는 데이터를 호출하거나 관리하는 객체입니다.\r\n\r\nDataset 객체와의 단방향 바인딩 및 REST API 호출 기능을 지원합니다.\r\n\r\nDataobject의 request 메소드를 사용하여 서버와 통신할 수 있습니다.\r\n이 경우 XMLHttpRequest 객체가 내부적으로 사용됩니다.",
	},
	"download": {
		"download": "다운로드",
		"ios": "다운로드 iOS",
		"macos": "다운로드 macOS",
		"android": "다운로드 Android",
		"windows64": "다운로드 Windows 64 bit",
		"windows32": "다운로드 Windows 32 bit"
	}
}