if (!nexacro.translation) {
    nexacro.translation = {};
}
nexacro.translation["zh-CN"] = {
    "인사": "你好 {{name}}",
    "error": {
        "invalid": "无效值"
    },
	"warn":{
		"quit":"你确定要辞职吗？",
		"menulimit": "菜单不能超过10个。",
		"menuidnotexist":"菜单 ID 不存在。"
	},	
    "Animation":"动画片",
    "Application sample":"应用样本",
    "Average":"平均数",
    "Bidirectional data binding":"双向数据绑定",
    "Capacity Usage":"容量使用情况",
    "Category grid":"类别网格",
    "Chart":"图表",
    "Close all":"全部关闭",
    "Component":"组件",
    "Component dynamic creation":"组件动态创建",
    "Components":"组件",
    "Content":"内容",
    "Convenient component placement":"方便的组件配置",
    "Convenient responsive web development":"方便的响应性Web开发",
    "Daily":"每日一次",
    "Dataset":"数据集",
    "Dynamic grid":"动态网格",
    "Dynamic tree grid":"动态树网格",
    "Easy data visualization component":"简单的数据可视化组件",
    "Effectively Driven data on":"有效驱动数据",
    "Excel\r\r\nImport/Export":"Excel\n导入/导出",
    "Excel Formula Import / Export":"导入/导出 Excel 公式",
    "Experience it on mobile!":"用手机体验吧！",
    "Extension component":"扩展组件",
    "File upload / download":"上传/下载文件",
    "Fit To Contents":"适合目录",
    "Google Map":"Google地图",
    "Grid":"网格",
    "Grid Component":"网格组件",
    "Grid cursor movement":"移动网格光标",
    "Guide":"指南",
    "Large data inquiry":"大数据查询",
    "List view":"列表视图",
    "Log":"日志",
    "MENU":"菜单",
    "Nexacro Chart":"Nexacro图表",
    "Open all":"全部打开",
    "Personalization settings":"个性化设定",
    "Portlet screen":"Portlet画面",
    "Quick Menu":"快速菜单",
    "Recently accessed menu":"最近访问的菜单",
    "Sample":"样本",
    "Screen personalization":"屏幕个性化",
    "Send Message":"发送消息",
    "Send post data to Server":"向服务器发送投稿数据",
    "Static, Edit, MaskEdit, TextArea":"静态、编辑、掩码编辑、文本区域",
    "Support\r\nMultilingual":"支持\n多语言",
    "Tab, GroupBox, ProgressBar":"标签、GroupBox、进度栏",
    "To Users":"致用户",
    "Total Views":"总视图",
    "Tree grid":"树栅",
    "TreeGrid/\r\nGrouping":"树网格/\n分组",
    "Use external modules":"使用外部模块",
    "Various components":"各种组件",
    "Various grid expressions":"各种网格表达式",
    "Various grid functions":"各种网格功能",
    "Various menu expressions":"多种菜单表达式",
    "WeChat":"微信",
    "Weekly":"周报",
    "Weekly Report":"每周报告",
    "nexacro Chart":"Nexacro图表",
    "nexacro platform demo":"Nexacro演示",
    "pivot":"枢轴",
	"companyContact": "首尔江南区奉恩寺路617号 | 代表电话:02-2140-7700\nCOPYRIGHT(C) BY 2017 TOBE SOFTWARE TECHNOLOGY（TIANJIN）Co., Ltd. ALL RIGHTS RESERVED",	
	"wechatsample": {
		"alert": {
			"touser":"请填写致用户字段。",
			"content":"请填写内容字段。"
		},	
		"explain": "Data 对象是调用或管理数据的对象。\r\n\r\n支持RESTAPI调用功能和数据集对象的单向绑定。\r\n\r\n可以使用数据对象的请求方法与服务器通信。\r\n在这种情况下，XMLHttpRequest 对象在内部使用。",
	},
	"download": {
		"download": "立即下载",
		"ios": "立即下载 iOS",
		"macos": "立即下载 macOS",
		"android": "立即下载 Android",
		"windows64": "立即下载 Windows 64位",
		"windows32": "立即下载 Windows 32位"
	}
}