if(!nexacro.translation) {
    nexacro.translation = {};
}
nexacro.translation["en"] = {
    "인사": "Hello world {{name}}",
    "error": {
        "invalid": "invalid value"
    },
	"warn":{
		"quit":"Are you sure you want to quit?",
		"menulimit": "You can not open more than 10 menus.",
		"menuidnotexist":"Menu ID does not exist."
	},
	"Animation":"Animation",
	"Application sample":"Application sample",
	"Average":"Average",
	"Bidirectional data binding":"Bidirectional data binding",
	"Capacity Usage":"Capacity Usage",
	"Category grid":"Category grid",
	"Chart":"Chart",
	"Close all":"Close all",
	"Component":"Component",
	"Component dynamic creation":"Component dynamic creation",
	"Components":"Components",
	"Content":"Content",
	"Convenient component placement":"Convenient component placement",
	"Convenient responsive web development":"Convenient responsive web development",
	"Daily":"Daily",
	"Dataset":"Dataset",
	"Dynamic grid":"Dynamic grid",
	"Dynamic tree grid":"Dynamic tree grid",
	"Easy data visualization component":"Easy data visualization component",
	"Effectively Driven data on":"Effectively Driven data on",
	"Excel\r\r\nImport/Export":"Excel\nImport/Export",
	"Excel Formula Import / Export":"Excel Formula Import / Export",
	"Experience it on mobile!":"Experience it on mobile!",
	"Extension component":"Extension component",
	"File upload / download":"File upload / download",
	"Fit To Contents":"Fit To Contents",
	"Google Map":"Google Map",
	"Grid":"Grid",
	"Grid Component":"Grid Component",
	"Grid cursor movement":"Grid cursor movement",
	"Guide":"Guide",
	"Large data inquiry":"Large data inquiry",
	"List view":"List view",
	"Log":"Log",
	"MENU":"MENU",
	"Nexacro Chart":"Nexacro Chart",
	"Open all":"Open all",
	"Personalization settings":"Personalization settings",
	"Portlet screen":"Portlet screen",
	"Quick Menu":"Quick Menu",
	"Recently accessed menu":"Recently accessed menu",
	"Sample":"Sample",
	"Screen personalization":"Screen personalization",
	"Send Message":"Send Message",
	"Send post data to Server":"Send post data to Server",
	"Static, Edit, MaskEdit, TextArea":"Static, Edit, MaskEdit, TextArea",
	"Support\r\nMultilingual":"Support\nMultilingual",
	"Tab, GroupBox, ProgressBar":"Tab, GroupBox, ProgressBar",
	"To Users":"To Users",
	"Total Views":"Total Views",
	"Tree grid":"Tree grid",
	"TreeGrid/\r\nGrouping":"TreeGrid/\nGrouping",
	"Use external modules":"Use external modules",
	"Various components":"Various components",
	"Various grid expressions":"Various grid expressions",
	"Various grid functions":"Various grid functions",
	"Various menu expressions":"Various menu expressions",
	"WeChat":"WeChat",
	"Weekly":"Weekly",
	"Weekly Report":"Weekly Report",
	"nexacro Chart":"Nexacro Chart",
	"nexacro platform demo":"Nexacro Demo",
	"pivot":"Pivot",
	"companyContact": "60 Mall Road, Suite 310, Burlington MA 01803 | TEL : 781-345-5500\nCOPYRIGHT(C) BY 2020 TOBESOFT.CO.LTD. ALL RIGHTS RESERVED",	
	"wechatsample": {
		"alert": {
			"touser":"Please fill in the To Users field.",
			"content":"Please fill in the Content field."
		},
		"explain": "A Dataobject is an object that calls or manages data.\r\n\r\nIt supports REST API call function and one-way binding with Dataset object.\r\n\r\nYou can communicate with the server using the dataobject's request method.\r\nIn this case, the XMLHttpRequest object is used internally.",
	},
	"download": {
		"download": "DOWNLOAD",
		"ios": "Download for iOS",
		"macos": "Download for macOS",
		"android": "Download for Android",
		"windows64": "Download for Windows 64 bit",
		"windows32": "Download for Windows 32 bit"
	}

}